<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="Lenovo-PC" name="Suit1.DateValidationTestCase" tests="4" failures="1" timestamp="27 May 2020 06:59:56 GMT" time="42.697" errors="0">
  <testcase name="valdiateLanguageSupportDateParser" time="9.197" classname="Suit1.DateValidationTestCase">
    <skipped/>
  </testcase> <!-- valdiateLanguageSupportDateParser -->
  <testcase name="valdiateLanguageSupportDateParser" time="8.854" classname="Suit1.DateValidationTestCase">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Wed May 27 09:00:00 UTC 2020] but found [Invalid date]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Wed May 27 09:00:00 UTC 2020] but found [Invalid date]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Suit1.DateValidationTestCase.valdiateLanguageSupportDateParser(DateValidationTestCase.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
    </failure>
  </testcase> <!-- valdiateLanguageSupportDateParser -->
  <testcase name="valdiateLanguageSupportDateParser" time="13.437" classname="Suit1.DateValidationTestCase">
    <skipped/>
  </testcase> <!-- valdiateLanguageSupportDateParser -->
  <testcase name="validateDateParseFormat" time="11.209" classname="Suit1.DateValidationTestCase"/>
</testsuite> <!-- Suit1.DateValidationTestCase -->
